### ISSUE TITLE
Explanation on how to get actual Json Format

### ISSUE THREAD

**Issue by jannickj** [VerifyTests/Verify#152]
I've spent a good 15 mins trying to figure out which api changes the JsonTextWriter. 

Also I think if you have something called "Json" then it should be json otherwise make a new format. The problem is you might "think" it looks better but if it's not json then other json based tooling will not work with it.

Also while we're at it where can I find how to change the source directory for all the received files?

**Comment by SimonCropp** [comment]
> other json based tooling will not work with it.

what tooling are you using?

**Comment by jannickj** [comment]
`jq` / `vscode highlighting` etc.

**Comment by SimonCropp** [comment]
here is the doco for serialization https://github.com/VerifyTests/Verify/blob/master/docs/serializer-settings.md

**Comment by jannickj** [comment]
I read I still can't figure it out.

**Comment by SimonCropp** [comment]
ok i will add some more doco

also how about a “strict-json” option?

and if it was strict json, what would expect the file extension to be?

**Comment by jannickj** [comment]
what is the different between "strict-json" and "json"?

**Comment by SimonCropp** [comment]
the problem is json is not an ideal format for doing comparisons. for example newline escaping makes long strings very difficult to compare. also quoting names add no value. 

this tool uses newtonsoft as a way to convert to a text representation. the result is no meant tobe json even if it looks similar.

 hence the extension is text. using a custom extension would mess with diff tools, git tools, and git newline settings

i dont thing enabling syntax highlighting in diff tools is a better default option given the above compromises

if you want a toggle where you can switch back to the default newtonsoft rendering i am happy to consider that

**Comment by jannickj** [comment]
@SimonCropp yeah that's reasonable :), but it would just be great if the library was more clear about it not actually being json. and there was an easy option to use to change it to actual json

**Comment by SimonCropp** [comment]
re docs around “not json” there is this https://github.com/VerifyTests/Verify#not-valid-json

re an option to make it real json, i am happy to consider a pull request
