### ISSUE TITLE
WIP: Extension setting is being ignored.

### ISSUE THREAD

**Issue by danielcweber** [VerifyTests/Verify#307]
I'll be investigating this further next week, but only so much for the time being:
In Verify 10.9.1, the extension setting seems to be ignored. Although I set it to "json", Verify fails with *received.txt" files.

Verification is being called like this:
```
var settings = new VerifySettings();
settings.UseExtension("json");

return Verifier.Verify(element, settings);
```

I could debug it as far as you can see on the pictures below. As I wrote, I'll put more effort into it after the weekend.

![image](https://user-images.githubusercontent.com/1899410/109348229-89e5a480-7874-11eb-8624-d9707471d938.png)
![image](https://user-images.githubusercontent.com/1899410/109348315-a681dc80-7874-11eb-99d3-ad325a069787.png)

**Comment by SimonCropp** [comment]
can you share a minimal repro for this?

**Comment by danielcweber** [comment]
Will do. I got into this a little bit deeper last week and also found out where the extension is being determined, but couldn't figure out where the logic got it wrong eventually.

**Comment by danielcweber** [comment]
I worked around this with VerifierSettings.UseStrictJson().

**Comment by danielcweber** [comment]
Repro in #310. The changes in d3ccb1c seem to have broken it.

**Comment by SimonCropp** [comment]
so a little history. initially verify produced correct json. but that was not ideal. for example:

 * json escapes newlines, so when multiple newlines are in a string, it doesnt wrap 
 * json escapes quotes making it very noisy when values contain many quotes

So Verify moved to a "json like" syntax https://github.com/VerifyTests/Verify/blob/master/docs/serializer-settings.md#not-valid-json . And since it was no longer valid json, and would break editor highlighting, the extension was moved to txt. Some people still wanted pure json. so VerifierSettings.UseStrictJson was added.  

So in the context of the above it doesnt make sense to use json as an extension when not using UseStrictJson

**Comment by danielcweber** [comment]
Thanks for the explanation - in addition to the docs, it makes perfect sense. I wasn't aware of this tbh. I just figured that if v9 creates .json files and v10 doesn't, it's got to be a bug somewhere. The bad thing is, this might not be immediately obvious, especially when using AutoVerify. So all my tests were green but the git status was full of changes. In case that !UseStrictJson && Extension != .txt, should it maybe throw early?

**Comment by SimonCropp** [comment]
> In case that !UseStrictJson && Extension != .txt, should it maybe throw early?

it should do this already

**Comment by danielcweber** [comment]
I'm using txt now everywhere and don't force UseStrictJson, things are much simpler that way. Thanks for everything!
