### ISSUE TITLE
Add support for PdfPig

### ISSUE THREAD

**Issue by asbjornu** [VerifyTests/Verify#507]
#### Describe the solution

> [PdfPig](https://uglytoad.github.io/PdfPig/) is a fully open-source Apache 2.0 licensed and .NET Standard compatible library that enables users to read and create PDFs in C#, F# and other .NET languages. It supports all versions of .NET back to .NET 4.5.

It would be awesome to have PdfPig integrated with Verify so PDF verification could be done without any commercial licensing.

#### Describe alternatives considered

Alternatives to PdfPig in Verify already exists, but they all require commercial licensing fees. PdfPig is free.

**Comment by SimonCropp** [comment]
I can take a look. but in pdfpig, how do you convert a pdf page to an png?

Note that  https://github.com/VerifyTests/Verify.ImageMagick supports verification pf pdfs and is free

**Comment by asbjornu** [comment]
I'm not sure PdfPig supports conversion to an image, but it does support text extraction. Perhaps @uglytoad has an idea for how PdfPig could be best utilized to compare the equality of two PDF files?

**Comment by SimonCropp** [comment]
i added initial support here https://github.com/VerifyTests/Verify.PdfPig
thoughts?

**Comment by asbjornu** [comment]
Wow, that was quick! That looks like a nice implementation to me, but I'm neither a PDF nor PdfPig expert. Perhaps @EliotJones can do a quick review?

**Comment by EliotJones** [comment]
You're correct that PdfPig doesn't currently have support for converting pages to images, it's something we'd like to add but the project is currenly more in maintenance than new feature mode due to life getting in the way.

In terms of the linked verification implementation it looks good to me. One note is that `page.Text` is the raw stream of text content operators written to the body of the PDF. In a lot of cases this will not include whitespaces and can be written out-of-order since the format prioritizes display over preserving semantic meaning.

There are a couple of ways to pull out text in a more human readable format but they have their own drawbacks for a verification check:
- From word detection: https://github.com/UglyToad/PdfPig/blob/master/examples/OpenDocumentAndExtractWords.cs
- Using in-built extractor: https://github.com/UglyToad/PdfPig/blob/master/examples/ExtractTextWithNewlines.cs

The drawback being that they're heuristics based and therefore could change. I wonder if it would be worth writing the version of the PdfPig library used by the library to the output so that you can easily see why there's some change between text using e.g. 0.1.5 vs 0.1.7?

Depending on the use-case there's further things such verification would catch, images are exposed by the API but the support is at a basic level but might be important for end-users. Finding JavaScript isn't currently supported by the library but can expose a security risk for PDF consumers, depending on what the aim of the verification is, this might be important.

**Comment by SimonCropp** [comment]
@EliotJones 

so [ExtractTextWithNewlines.cs](https://github.com/UglyToad/PdfPig/blob/master/examples/ExtractTextWithNewlines.cs) is much better. i will deploy a new version of Verify.PdfPig using that now

and nice work with PDFpig

**Comment by asbjornu** [comment]
While it's wonderful with PdfPig support in Verify, I'm having some problems getting this to work for me. The reason is that I'm having an application where PDFs are generated on several different operating systems and would like to verify that wherever they are generated, they contain the expected text. 

For some reason, the current algorithm (in either Verify or PdfPig) causes PDFs created on Windows to yield a different textual output than PDFs created on Mac. Visually, there's very little separating the PDFs from each other, but the extracted text is not equal at all. For instance, in the Mac-generated PDF, all words are separated by tabs instead of spaces. Also, lines break at different places, causing text to appear on different pages as well. All of these discreapancies amount to different extracted textual output, causing verification to fail.

I've tried to implement a custom scrubber plugged into Verify to normalize tabs to spaces, break all lines at 120 characters, etc., but since some words appear on different pages in Windows vs. Mac, there's header content in-between pages that mess up the normalization and also cause the verification to fail. Example:

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
(Page 1 of 10) Proin sodales eros et ipsum suscipit, nec
```

vs.

```
Lorem ipsum dolor sit amet, consectetur adipiscing (Page 
1 of 10) elit. Proin sodales eros et ipsum suscipit, nec
```

Notice the placement of `(Page 1 of 10)`. This comes from a repeated header that is extracted and is displeased by one word in the Windows vs. Mac PDF. Another weirdness about my scrubber is that it not only breaks the content of the PDF, but the entire JSON-like output from Verify.

So I'm wondering whether something like `PDFTextStripper` suggested in UglyToad/PdfPig#180 or an algorithm based on `Page.GetWords()` as in [`OpenDocumentAndExtractWords.cs`](https://github.com/UglyToad/PdfPig/blob/c2ecb7853b6e78fa4fc46b092103af3fd4bd3148/examples/OpenDocumentAndExtractWords.cs) may provide a more lenient and thus more robust verification mechanism?

Thoughts @EliotJones, @SimonCropp?

**Comment by asbjornu** [comment]
The issue I'm facing is exacerbated by UglyToad/PdfPig#439 as well.
